# -*- coding: utf-8 -*-
"""
Created on Sun Mar 22

@author: Jay Brydon

Investigation into how well the log-gamma distribution is approximated by
a normal distribution.

Code is generated by Gemini.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import gamma, norm, gaussian_kde

# 1. Define alpha and beta
alpha = 9
beta = 0.5  # Rate parameter
scale = 1.0 / beta  # SciPy and NumPy use scale = 1/beta
size = 50000

# 2. Sample from the Gamma distribution
gamma_sample = np.random.gamma(alpha, scale, size)

# 3. Log the sample (Log-Gamma sample)
log_gamma_sample = np.log(gamma_sample)

# 4. Compute mean and variance of the logged sample
mean_log = np.mean(log_gamma_sample)
var_log = np.var(log_gamma_sample)
std_log = np.sqrt(var_log)

# Plotting
fig, axes = plt.subplots(2, 1, figsize=(10, 10))

# --- Top Row: Original Gamma ---
x_gamma = np.linspace(0, np.max(gamma_sample), 1000)
# Exact PDF
axes[0].plot(x_gamma, gamma.pdf(x_gamma, alpha, scale=scale), 
             'r-', lw=2, label='Exact Gamma PDF')
# Sample KDE
kde_gamma = gaussian_kde(gamma_sample)
axes[0].plot(x_gamma, kde_gamma(x_gamma), 
             'b--', label='Sample KDE')

axes[0].set_title(f'Original Gamma Distribution ($\\alpha={alpha}, \\beta={beta}$)')
axes[0].set_xlabel('Value')
axes[0].set_ylabel('Density')
axes[0].legend()

# --- Bottom Row: Log-Gamma vs Normal ---
x_log = np.linspace(np.min(log_gamma_sample) - 1, np.max(log_gamma_sample) + 1, 1000)
# Logged Sample KDE
kde_log = gaussian_kde(log_gamma_sample)
axes[1].plot(x_log, kde_log(x_log), 
             'b-', lw=2, label='Logged Sample KDE')
# Corresponding Normal PDF
axes[1].plot(x_log, norm.pdf(x_log, mean_log, std_log), 
             'g--', label=f'Normal ($\mu={mean_log:.2f}, \sigma^2={var_log:.2f}$)')

axes[1].set_title('Logged Sample KDE vs. Normal Approximation')
axes[1].set_xlabel('Log Value')
axes[1].set_ylabel('Density')
axes[1].legend()

plt.tight_layout()
plt.show()

print(f"Computed Log-Gamma Mean: {mean_log:.4f}")
print(f"Computed Log-Gamma Variance: {var_log:.4f}")
